apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: nginx
              image: nginx
              ports:
              - containerPort: 80
              env:
              - name: FOO
                value: BAR
              - name: MICROSERVICE
                value: java-backend
              resources:
                requests:
                  memory: 0.5G
                  cpu: 100m
                limits:
                  memory: 1G
                  cpu: 200m
              livenessProbe:
                  httpGet:
                      path: /
                      port: 80
                  initialDelaySeconds: 15
                  periodSeconds: 10
                  failureThreshold: 3
              readinessProbe:
                  httpGet:
                      path: /
                      port: 80
                  periodSeconds: 10 
              