apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data-1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-2
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data-2"

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-3
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data-3"