apiVersion: v1
kind: Service
metadata:
  name: mongo-statefulset-headless
spec:
  ports:
  - port: 27017
  clusterIP: None
  selector:
    app: mongo-statefulset

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - port: 27017
  selector:
    app: mongo-statefulset

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongo-statefulset
spec:
    selector:
        matchLabels:
            app: mongo-statefulset
    serviceName: mongo-statefulset-headless
    replicas: 1
    template:
        metadata:
            labels:
                app: mongo-statefulset
        spec:
            containers:
            - name: mongo
              image: mongo
              ports:
              - containerPort: 27017
              env:
              - name: MONGO_INITDB_ROOT_USERNAME
                value: javaapp
              - name: MONGO_INITDB_ROOT_PASSWORD
                value: java123
              resources:
                requests:
                  memory: 0.5G
                  cpu: 100m
                limits:
                  memory: 1G
                  cpu: 200m
              livenessProbe:
                  tcpSocket:
                    port: 27017
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  failureThreshold: 3
              readinessProbe:
                  tcpSocket:
                    port: 27017
                  periodSeconds: 10
              volumeMounts:
              - name: data
                mountPath: /data/db
    volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 3Gi