apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    app: mysql
provisioner: kubernetes.io/no-provisioner