apiVersion: v1
kind: ServiceAccount
metadata:
  name: javaapp

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: javaapp-read-services
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: javaapp-read-services
subjects:
- kind: ServiceAccount
  name: javaapp
roleRef:
  kind: Role
  name: javaapp-read-services
  apiGroup: rbac.authorization.k8s.io